// `npm run build:web` -- the client as a plain web page, in client/www.
//
// The same renderer the desktop app loads, made to stand on its own:
//
//   * src/renderer is copied as it is. With no Electron preload there is no
//     window.harmony, so bridge.js builds `harmony` from web/bridge.js.
//   * mp4-muxer is copied in under vendor/, which the desktop serves straight
//     out of node_modules through its harmony:// protocol.
//   * web/build-info.js is generated: the default settings, read from
//     src/main/settings.js so there is one list of them, and the version.
//   * The Content-Security-Policy is widened. The desktop page may not touch
//     the network at all -- main does that for it -- while this one talks to
//     the server itself: fetch, WebSocket, and <img>/<audio> from it.
//
// client/www is what Capacitor wraps into the Android app (capacitor.config.json)
// and what `npm run web` serves for trying it in a browser.

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const Module = require('node:module');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'www');

/** Load src/main/settings.js for its DEFAULTS, with Electron stubbed out. */
function readDefaults() {
  const load = Module._load;
  Module._load = function stubElectron(request, ...rest) {
    if (request === 'electron') return { app: { getPath: () => os.tmpdir() } };
    return load.call(this, request, ...rest);
  };
  try {
    return require(path.join(ROOT, 'src', 'main', 'settings.js')).DEFAULTS;
  } finally {
    Module._load = load;
  }
}

const WEB_CSP = [
  "default-src 'self'",
  "connect-src 'self' http: https: ws: wss: data: blob:",
  "img-src 'self' http: https: data: blob:",
  "media-src 'self' http: https: blob: mediastream: data:",
  "style-src 'self'",
  "script-src 'self'",
].join('; ');

function build() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.cpSync(path.join(ROOT, 'src', 'renderer'), OUT, { recursive: true });

  // The package's exports map hides package.json, so it is found by path.
  const muxer = path.join(ROOT, 'node_modules', 'mp4-muxer', 'build');
  fs.cpSync(muxer, path.join(OUT, 'vendor', 'mp4-muxer', 'build'), { recursive: true });

  const { version } = require(path.join(ROOT, 'package.json'));
  fs.writeFileSync(
    path.join(OUT, 'web', 'build-info.js'),
    '// Generated by scripts/build-web.js. Do not edit.\n'
      + `export const VERSION = ${JSON.stringify(version)};\n`
      + `export const DEFAULTS = ${JSON.stringify(readDefaults(), null, 2)};\n`,
  );

  const indexPath = path.join(OUT, 'index.html');
  const html = fs.readFileSync(indexPath, 'utf8');
  const patched = html.replace(
    /(http-equiv="Content-Security-Policy"\s+content=")[^"]*(")/,
    `$1${WEB_CSP}$2`,
  );
  if (patched === html) throw new Error('build-web: the CSP meta tag in index.html was not found');
  fs.writeFileSync(indexPath, patched);

  console.log(`[build-web] ${version} -> ${path.relative(process.cwd(), OUT) || OUT}`);
}

build();
